// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1HJQ8gCnZ1dAK0o-ERlLyOBukWga3Dps',
    appId: '1:596399747115:web:b1e3542a74fef9c907ba6e',
    messagingSenderId: '596399747115',
    projectId: 'rstudio-e670f',
    authDomain: 'rstudio-e670f.firebaseapp.com',
    storageBucket: 'rstudio-e670f.firebasestorage.app',
    measurementId: 'G-859TCTF76V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmdo26sfnmkB4sgok1SApvgIjQIzsLWoY',
    appId: '1:596399747115:android:ed5f23694d1a053e07ba6e',
    messagingSenderId: '596399747115',
    projectId: 'rstudio-e670f',
    storageBucket: 'rstudio-e670f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3gqZaZXx59yO6zkpFEG6ybPHJ1m6c_3g',
    appId: '1:596399747115:ios:e8a847bdfb2e554607ba6e',
    messagingSenderId: '596399747115',
    projectId: 'rstudio-e670f',
    storageBucket: 'rstudio-e670f.firebasestorage.app',
    iosBundleId: 'com.example.rStudioV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3gqZaZXx59yO6zkpFEG6ybPHJ1m6c_3g',
    appId: '1:596399747115:ios:e8a847bdfb2e554607ba6e',
    messagingSenderId: '596399747115',
    projectId: 'rstudio-e670f',
    storageBucket: 'rstudio-e670f.firebasestorage.app',
    iosBundleId: 'com.example.rStudioV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1HJQ8gCnZ1dAK0o-ERlLyOBukWga3Dps',
    appId: '1:596399747115:web:bab322a44a4c602807ba6e',
    messagingSenderId: '596399747115',
    projectId: 'rstudio-e670f',
    authDomain: 'rstudio-e670f.firebaseapp.com',
    storageBucket: 'rstudio-e670f.firebasestorage.app',
    measurementId: 'G-L0KJXK1N9V',
  );
}
